---
- name: Setting up the environment
  hosts: localhost
  gather_facts: no
  vars: 
    AWS_REGION: "eu-central-1"
    AWS_SECURITY_GROUP: "dekel_test"
    TAG: 
       EnvName: "Test Environment"
  tasks:
    - include_role: 
        name: security-group
      register: security
    - include_role: 
        name: linux-ec2 
