---
- name: Setting up the environment
  hosts: localhost
  gather_facts: no
  vars: 
    AWS_REGION: "eu-central-1"
    AWS_SECURITY_GROUP: "dekel_test"
    TAG: 
       EnvName: "Test Environment"
  tasks:
# maybe we will need to use import!
    - name: Setting up security group
      include_role: 
        name: security-group
      register: security
    - include_role: 
        name: linux-ec2 

- name: Configure instance(s)
  hosts: launched
  gather_facts: no
  roles: 
    - setting_nginx

- name: Terminate instances
  hosts: localhost
  gather_facts: no
  tasks:
  - name: enter keyword to remove the instance
    pause:
      prompt: "enter keyword: "
      echo: yes

  - name: Terminate instances that were previously launched
    ec2:
      state: 'absent'
      instance_ids: '{{ ec2.instance_ids }}'
