---
- name: creating ec2 linux
  ec2:
    #aws_secret_key: "{{ AWS_SECRET_KEY }}"
    #aws_access_key: "{{ AWS_ACCESS_KEY }}" 
    region: "{{ AWS_REGION }}"
    instance_type: "{{ INSTANCE_TYPE }}"
    image: "{{ AMI }}"
    group: "{{ AWS_SECURITY_GROUP }}"
    instance_tags: "{{ TAG }}"
    wait: True
  register: ec2

- name: enter keyword to remove the instance
  pause:
    prompt: "keyword: "
    echo: yes

- name: Terminate instances that were previously launched
  ec2:
    state: 'absent'
    region: "{{ AWS_REGION }}"
    instance_ids: '{{ ec2.instance_ids }}'

