---
- name: create ec2 security groups
  ec2_group:
    name: "{{ name }}"
    description: setting up security group for the test
    region: "{{ AWS_REGION }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    rules:
      - proto: tcp
        ports:
        - 80 
        - 22
        cidr_ip: 192.168.10.1/24
    rules_egress:
      - proto: tcp
        ports: 
        - 80
        - 443
        cidr_ip: 0.0.0.0/0
