---
- name: create ec2 security groups
  ec2_group:
    name: "{{ AWS_SECURITY_GROUP }}" 
    description: setting up security group for the test
    region: "{{ AWS_REGION }}"
    tags:  "{{ TAG }}"
    rules:
      - proto: tcp
        ports:
        - 80 
        - 22
        cidr_ip: "{{ MY_SUBNET_IP }}"
      - proto: tcp
        ports:
        - 22 
        cidr_ip: "{{ ANSIBLE_HOST }}"
    rules_egress:
      - proto: tcp
        ports: 
        - 80
        - 443
        cidr_ip: "{{ OUTBOUND }}"
